
services:
  mcpharm:
    image: mcpharm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcpharm
    ports: 
      - "8080:8000"
    volumes: 
      - C:/Users/HP/OneDrive/Documents/GitHub/Online-Pharmacy/MCPharm:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: users
      DB_PASSWORD: SoMeUsEr.101
      DB_NAME: mcpharm
      DB_PORT: 3306

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Meli9464.$
      MYSQL_DATABASE: mcpharm
      MYSQL_USER: users
      MYSQL_PASSWORD: SoMeUsEr.101
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
