-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Sep 21, 2024 at 12:52 PM
-- Server version: 8.3.0
-- PHP Version: 8.2.18

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `mcpharm`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

DROP TABLE IF EXISTS `products`;
CREATE TABLE IF NOT EXISTS `products` (
  `Product_id` int NOT NULL DEFAULT '0',
  `Product_Name` varchar(255) NOT NULL DEFAULT '',
  `Brief_Description` varchar(255) NOT NULL DEFAULT '',
  `Price` double NOT NULL DEFAULT '0',
  `Product_Description` mediumtext NOT NULL,
  `Image_path` mediumtext,
  `Category_id` int DEFAULT NULL,
  `Category` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`Product_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`Product_id`, `Product_Name`, `Brief_Description`, `Price`, `Product_Description`, `Image_path`, `Category_id`, `Category`) VALUES
(42371, 'Panadol Extra Advance Tablets with Optizorb Formulation', 'Fight tough pain with Panadol Extra Advance tablets with OPTIZORB, a pain reliever that combines paracetamol and caffeine for faster absorption than standard paracetamol tablets. Effective pain relief when you need it.', 10, 'Fast-acting pain relief tablet that combines the power of paracetamol with caffeine to provide extra strength against tough pains like headaches, migraines, toothaches, and muscular aches. The advanced formula is designed to be absorbed quickly, offering rapid relief when you need it most. Safe on the stomach and effective for up to eight hours, it’s your go-to solution for managing pain and discomfort.', 'Images/Medications/Panadol extra.png', 1, 'Medications'),
(32473, 'Panadol Migraine 24 CT', 'Panadol Migraine Tablet: Powerful Over-the-Counter Migraine Relief Panadol Migraine Tablet is an effective over-the-counter solution for migraine treatment.\r\n', 8, '\r\nFast-acting pain relief tablet that combines the power of paracetamol with Panadol Migraine Tablet is an effective over-the-counter solution for migraine treatment. Clinical studies demonstrate that patients with moderate to severe migraines experienced effective relief with just one dose. Migraine symptoms can vary but often include pulsating or throbbing pain on one side of the head, accompanied by nausea, vomiting, and sensitivity to light and sound.', 'Images/Medications/Panadol migrane.jpg', 1, 'Medications'),
(25253, 'Imodium Instants Loperamide 2mg 12 Pack', 'Imodium works by restoring your bowel to its normal rhythm. This helps to restore the absorption of fluids into your body.', 13, 'Imodium Instants Loperamide 2mg tablets are used for the treatment of sudden, short-lived attacks of diarrhoea in adults and children 12 years and over. Imodium Instants are our most popular treatment for diarhhoea.', 'Images/Medications/Loperamide pills.jpg', 1, 'Medications'),
(18847, 'Pure Nutrition Papaya Complete', '60 Veg Capsules (Supports Platelet Immunity & Digestion) Each Capsule Contains 500mg Carica Papaya Fruit and Leaf Extract. Non-GMO | Gluten-Free', 25, 'Nutraceuticals are foods that offer health benefits to the consumer. Papaya Complete Helps to : Key Ingredient : 1- Papaya leaf, fruit extract, vitamin A and vitamin C. Suggested Use : 1- Take 1 Capsules twice daily with or after meal. Papaya Complete Can Help Improve Platelet Immunity & Digestion Increases in platelet and RBC counts - Papaya leaves contain various phytoconstituents like tannins, cardiac glycosides saponins, and alkaloids. Enzymes of Papaya helps in digestion - Papaya fruit is a rich source of valuable proteolytic enzymes, such as papain, chymopapain, caricain and glycyl endopeptidase.', 'Images/Medications/Papaya extract.jpg', 1, 'Medications'),
(98476, 'Allergy Pills by Hyland’s, Non Drowsy Seasonal Allergy Relief', 'Safe and Natural for Indoor & Outdoor Allergies, 60 Quick Dissolving Tablets', 22.46, 'Hyland’s Seasonal Allergy Relief Tablets is safe and non-habit forming. Our gentle homeopathic formulas are made with all natural active ingredients. There are no known side-effects and will not conflict with any medications you may be taking. Hyland’s provides the highest standard of quality.', 'Images/Medications/Allergy medication.jpg', 1, 'Medications'),
(65842, 'Nurofen Cold & Flu 200mg/30mg Film Coated Tablets', 'Nurofen Cold & Flu Tablets contain a pain reliever and decongestant to tackle cold and flu symptoms.', 11.99, 'Nurofen Cold and Flu Tablets are film-coated tablets used to relive nasal congestion and the symptoms of colds and flus, including headache, sore throat, body ache, fever and pain. Each tablet contains 200mg of Ibuprofen and 30mg Pseudoephedrine hydrochloride, a decongestant which relieves a blocked or runny nose. These tablets are non-drowsy.', 'Images/Medications/Nurofen.jpg', 1, 'Medications'),
(23780, 'Blood Glucose Monitor Kit Diabetes Testing Kit', 'Blood Glucose Monitor Kit Automatic LCD Display Glucose Meter Diabetes Testing Set for Home', 13.44, 'Simplify blood sugar testing with an integrated set that enables testing anytime, anywhere. The inclusion of automatic machine recognition for test strips helps prevent measurement errors, ensuring a user-friendly experience.', 'Images/Medications/Glucose meter.jpg', 1, 'Medications'),
(91375, 'Ventolin (salbutamol) | Asthma Inhaler', 'The active ingredient in the Ventolin asthma inhaler is (salbutamol sulphate), which helps to reduce the symptoms of an asthma attack or trouble breathing', 11, 'Ventolin Salbutamol blue reliever inhalers contain salbutamol (as sulfate) for quick relief of asthma and COPD symptoms. This short-acting bronchodilator is safe and effective for most adults and children, including pregnant and breastfeeding women.', 'Images/Medications/Asthma inhaler.jpg', 1, 'Medications'),
(15536, 'Healthy Care Vitamin C 500mg Chewable 500 Tablets', 'Supports Skin Health an Improves Immunity - Antioxidant Support - Premium Quality Dietary Supplement - 300 Tablets - 500 mg', 26.99, 'Maintain your health effortlessly with Healthy Care high potency vitamin C, available in a generous pack of 300 chewable tablets. This daily supplement is designed to strengthen your immune system, enhance skin health, and protect against environmental and cellular damage. The vitamin C chewable tablets help keep your skin looking its best and protect against everyday toxins and strains. Ideal for anyone looking to support their health naturally, these tablets ensure you get your daily dose of chewable vitamin C in the most convenient way possible.', 'Images/Supplements/Vitamin C.jpg', 2, 'Supplements'),
(63555, 'MedeVox Zinc Tablets 50Mg 30 Tablets', 'Zinc is an essential anti-oxidant trace element that strengthens immune system function and helps with the maintenance of normal skin and nails.', 6.99, 'MedeVox Zinc Tablets 50mg provide a potent dose of zinc to support immune function, skin health, and overall well-being. Each tablet contains 50mg of zinc, offering daily nutritional support in a convenient, easy-to-swallow form. The pack includes 30 tablets, perfect for a month’s supply.', 'Images/Supplements/Zinc tablets.jpg', 2, 'Supplements'),
(81166, 'Celestial Seasonings Chamomile Herbal Tea, Caffeine Free, 20 Tea Bags Box, (Pack of 6)', 'Chamomile tea comes from the chamomile flower and is not a tea in the traditional sense but rather an herbal beverage.', 19, 'Nothing is more soothing than a cup of your favorite tea. Celestial Seasonings Chamomile Herbal Tea is the perfect caffeine free addition to your daily routine. Chamomile flowers from around the world are blended to create a soothing cup in which you can take comfort anytime. Put some magic in your mug and enjoy the goodness found in every cup of Celestial Seasonings Teas. Celestial Seasonings teas are an invitation to put some magic in your mug! When we started Celestial Seasonings in 1969, we were inspired by the awesome power of nature right outside our door in the Rocky Mountains. We foraged the fields and forests for herbs and botanicals, creating unique and delicious blends as America’s first herbal tea company. Today we’re still crafting tea in Boulder, Colorado under the watchful eye of our Blendmaster, creating teas that are bursting with benefits, flavor, and our passion for inspiring a happier and wholesome life.', 'Images/Supplements/Chamomile herbal tea.jpg', 2, 'Supplements'),
(25165, 'Hovenia-RX Milk Thistle - Liver Support Supplement with 80% Silymarin Milk Thistle Seed Extract - 120 Tablets, 30 Day Supply', 'Maximum strength of Hovenia ducis extract , Milk Thistle (silymarin 80%) , Vitamin B1 & B2, Maintaining Healthier Liver Functions , Helps Liver Detox , Endurance Supports & Reducing Fatigue , Triglycerides & Glucose Level Support.', 50, 'Nanowell® Hovenia-Rx® Milk Thistle Tablet contains Hovenia ducis extract, which has approved for three functional abilities for liver protection, enhance endurance, fatigue maintenance by Korean Ministry of Food and Drug Safety, and it is the maximum strength on the market today. It also contains milk thistle extract (standardized to silymarin 80%), chromium, and zinc', 'Images/Supplements/Hovenia herbal supplement.jpg', 2, 'Supplements'),
(52327, 'Ultimate Weight Loss Package', 'Extreme Fat Metabolism.\r\nAll Day Energy & Focus.\r\nHunger Control.\r\nMeal Replacement.', 230, 'Reaching your weight loss goals doesn’t have to be hard. Get everything you need to support your journey and burn fat from all angles with this complete system. The Torch System will aggressively burn fat and calories faster while boosting energy. Carb Shield supports craving control and stops carbs from storing as fat. Lastly, Slim Smoothie is the perfect, delicious meal replacement for those on-the-go, helping to keep you feeling full while losing weight.', 'Images/Supplements/weight loss package.png', 2, 'Supplements'),
(86142, 'Premier Protein Powder, Vanilla Milkshake, 30g Protein1g, Sugar, 100% Whey Protein, Keto Friendly, No Soy Ingredients, Gluten Free, 17 Servings, 23.3 Ounces.', 'Sweet and smooth, this vanilla flavored protein powder helps pack in the nutrition you rely on every day while delivering indulgent taste like a bowl of creamy vanilla ice cream.', 46.99, 'Each serving of premier protein powder contains 30g Protein, 150 calories, and 1g Sugar. Gluten free & No Soy Ingredients. Made with 100% protein from Whey, it is perfect for use any time of the day, from breakfast to afternoon snack to post-exercise fuel. Try it mixed with water or milk, blended into your favorite smoothie recipe, or baked into protein packed recipes. Each canister contains 17 servings. Available in 3 delicious, indulgent flavors: Cafe Latte, Chocolate Milkshake and Vanilla Milkshake.', 'Images/Supplements/Protein powder.jpg', 2, 'Supplements'),
(15398, 'Basic Nutrients 2/Day Multivitamin/Multimineral', 'Comprehensive Daily Multivitamin with Optimal Bioavailability', 6.99, 'Complete two-capsule per day essential multivitamin/multimineral formula. The keystone of every nutritional product line is a multi-vitamin/mineral supplement. A multi-vitamin/mineral product is the starting point for every individual’s supplementation needs.', 'Images/Supplements/Thorne multivitamin.jpg', 2, 'Supplements'),
(83731, 'Sensodyne Fresh Gel Sensitive Toothpaste - 150 gm', 'Sensodyne Fresh gel provides sensitivity protection plus all the benefits you would expect from a daily toothpaste - strong teeth, healthy gums and fresh breath', 7.77, 'Sensodyne is specifically formulated to form a shield of 24x7 protection against sensitivity and provide relief, with twice daily brushing. Sensodyne is less abrasive than most ordinary toothpastes, hence is ideal for sensitive teeth. It contains fluoride that strengthens teeth and prevents decay. It leaves your mouth feeling fresh and clean.', 'Images/Dental Health/Sensodyne toothpaste.png', 3, 'Dental Health'),
(60228, 'Colgate Optic White Teeth Whitening Mouthwash with Optic Brightener, Alcohol Free 500mL', 'Colgate Optic White Mouthwash is alcohol free with optic brightener. Instantly whiter teeth and daily stain defence', 6.99, 'New Colgate optic white mouthwash contains 2% hydrogen peroxide to effectively whiten teeth by removing surface stains. This alcohol-free solution is available in a sparkling fresh mint flavor to freshen breath while whitening teeth and contains polyphosphates to prevent future stains. Dynamic foaming action reaches hard-to-brush places, helping to whiten teeth and freshen breath. For an extra white smile, use after brushing with Colgate optic white toothbrush and toothpaste.', 'Images/Dental Health/colgate mouthwash.jpg', 3, 'Dental Health'),
(39947, 'ORAL-B ESSENTIAL FLOSS WAXED', 'Oral-B Essential Floss Waxed removes plaque and food stuck in between teeth where all toothbrushes find it difficult to reach', 4.51, 'Cleans where your brush can’t reach. Shred-resistant. Brushing alone can’t get to all the hard-to-reach places where plaque builds up. But Oral-B EssentialFloss can. With its light wax coating and its shred-resistant texture, it slides easily between your teeth and below the gumline. It helps clean the tough-to-get plaque away. Used morning or evening when you brush, EssentialFloss helps your gums and your teeth stay healthy.', 'Images/Dental Health/Oral-B dental floss.jpeg', 3, 'Dental Health'),
(99052, 'ORAL-B VITALITY PLUS BLUE CROSS ACTION ELECTRIC TOOTHBRUSH POWERED BY BRAUN', 'The Oral-B Vitality Plus Cross Action electric rechargeable toothbrush provides a clinically proven superior clean vs• a regular manual toothbrush', 96, 'The Cross Action toothbrush head surrounds each tooth with bristles angled at 16 degrees, and 2D cleaning action oscillates and rotates for better plaque removal than a regular manual toothbrush. An in-handle timer helps you brush for a dentist-recommended 2 minutes. Compatible with the following replacement toothbrush heads: Cross Action, 3D White, Sensi Ultrathin, Sensitive Clean, Precision Clean, Floss Action, Tri Zone , Dual Clean, Power Tip, Ortho Care.', 'Images/Dental Health/Oral B toothbrush.png', 3, 'Dental Health'),
(95418, 'Vaseline Body Lotion Essential Healing, 725ml', 'Vaseline Essential Healing Lotion keep dry skin healed for three weeks. It contains micro-drops of Vaseline jelly, which are designed to lock in moisture and restore dull-looking skin', 25.99, 'Vaseline Intensive Care Essential Healing Body Lotion provides fast absorbing moisture to give you deeply moisturized, healthy looking skin. Clinically proven to keep dry skin healed for 3 weeks, after four weeks of daily use, its a body lotion you can count on. Deeply Moisturizing Lotion. The Vaseline Essential Healing Body Lotion moisturizes deep down to heal dry skin. Everyday, your skin is exposed to damaging environmental factors like extreme temperatures, low humidity, harsh cleansers, and hot water.', 'Images/Cosmetics/Vaseline lotion.jpg', 4, 'Cosmetics'),
(79937, 'Coppertone SPORT Sunscreen SPF 50 Lotion, Water Resistant Sunscreen, Body Sunscreen Lotion, 7 Fl Oz', 'Water Resistant: Coppertone Sport SPF 50 sunscreen lotion is water resistant (80 minutes), and stays on strong when you sweat', 9.27, 'Whichever outdoor activity you’re passionate about, Coppertone Sport Sunscreen Lotion SPF 50 is on your team. This Broad Spectrum sunscreen is designed to stay on strong when you sweat, and this high-performance sunscreen lotion protects you from the sun with a durable and water resistant sunscreen formula (80 minutes). This Coppertone sunscreen lotion offers Broad Spectrum UVA/UVB protection in a moisturizing formula. Each sunscreen Coppertone creates follows a tradition of trusted, quality sun protection products. Coppertone has been providing continuous innovation for more than 75 years, and is voted the most trusted sunscreen brand.', 'Images/Cosmetics/Coppertone Sunscreen.jpg', 4, 'Cosmetics'),
(13429, 'Garnier Micellar Cleansing Water & Makeup Remover Vitamin C', 'Remover Vitamin C\r\nMicellar Cleansing Water with Vitamin C gently cleanses skin, removes makeup, and brightens dull skin in just one step, without harsh rubbing or rinsing', 8.95, 'This all-in-1 brightening Micellar Cleansing Water is a facial cleanser and makeup remover that is surprisingly powerful, yet gentle on skin. The Garnier Micellar Cleansing Water with Vitamin C works for all skin types. It effectively cleanses, removes makeup, and brightens skin. Like a magnet, micelles capture and lift away dirt, oil and makeup without harsh rubbing. This facial cleanser removes makeup, leaving skin perfectly clean without over drying.', 'Images/Cosmetics/garnier makeup remover.png', 4, 'Cosmetics'),
(87335, 'ADDICTION TOKYO THE NAIL POLISH +', 'high-performance nail polish that delivers vibrant color and long-lasting wear with a smooth, glossy finish. Its quick-drying formula ensures a flawless, salon-quality manicure at home', 19, 'Express yourself with fast-drying, long-wearing nail polish. The 10-free formula is 72% natural, vegan, and free from harmful ingredients. Each shade is high-gloss and flexible to resist cracks, peeling, and chipping, and allows oxygen to permeate for nail breathability.', 'Images/Cosmetics/Nail polish.jpg', 4, 'Cosmetics'),
(26390, 'Dior Sauvage Men’s Perfume 60ml', 'A radically fresh composition, with a powerful name that speaks for itself.That was the way François Demachy, Dior Perfumer-Creator, wanted it: raw and noble all at once', 189, 'Inspiration for the creation of Sauvage Eau de Parfum was taken from the desert in the magical hour of twilight: mixed with the coolness of the night, the burning desert air exudes profound scents. Sauvage Eau de Parfum is thus the olfactory interpretation of a moment tinted with a thick blue that unleashes the wildest instincts. In the hour when the wolves come out and the sky is set ablaze, a new magic unfolds.', 'Images/Cosmetics/Sauvage perfume.jpg', 4, 'Cosmetics'),
(39944, 'Dear Body Amber Dream Fragrance Body Mist For Women 250 ML', 'Dear Body perfume mist for women with beautiful designed packaging, the feminine aroma keeps your spirits high with class, style and elegance, fragrance mist gives you a more intense, longer lasting aroma', 11, 'Body mist has a much lower concentration than an Eau de Toilette or Eau de Parfum, making them great for everyday wear. They generally linger on the skin for two to three hours, so you’ll need to pop the body mist in your bag for top-ups throughout the day to enjoy the aroma for as long as possible. The eye-catching packaging of the body mists by Dear Body makes it a perfect gifting option, looks attractive and is super-easy to carry along. It is travel-friendly and affordable.', 'Images/Cosmetics/dearbody perfume.jpg', 4, 'Cosmetics'),
(20553, 'Garnier Color Naturals Nourishing Permanent Hair Color Cream', 'Try the Garnier Color Naturals Black Hair Color to get shiny and silky hair with a rich, natural black color that lasts up to 10 weeks. This hair color is ammonia-free and provides 100% grey coverage in just 30 minutes!', 15, 'Enriched with 10x natural oils, the Garnier Natural Black Hair Color leaves your hair looking vibrant, shiny, silky, and healthy. It is made with a no-ammonia crème formula, and comes with superior color lock technology that gives you a rich color that lasts up to 10 weeks. The nourishing, permanent Garnier black color comes in an easy-to-use kit that can be used as per your convenience.', 'C:Users/HP/OneDrive/Desktop/summer project 1/Images/Cosmetics/garnier hair dye.jpg', 4, 'Cosmetics'),
(62930, 'L’Oreal Paris Excellence Creme Triple Care Permanent Hair Color 5G Medium Golden Brown', 'Non-drip creme permanent hair color with New Triple Care Color routine that deeply cares for your hair. 100% gray hair coverage for all hair types', 12, 'New Triple Care Color routine protects before, during and after coloring for up to eight weeks, new look with same great shades. Your Excellence just got better, New salon inspired after color shampoo delicately cleanses the scalp and hair by gently rinsing away excess residue, Smoothes the hair to reveal its radiance. Rich, radiant hair color from root to tip with exclusive non-drip creme formula.', 'C:Users/HP/OneDrive/Desktop/summer project 1/Images/Cosmetics/loreal hair dye.jpeg', 4, 'Cosmetics');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
